<?php echo $this->headDoctype();?>
<html lang="fr">
	<head>
		<?php echo $this->headTitle();?>
		<?php echo $this->headMeta();?>
		<link rel="stylesheet" type="text/css" media="screen" href="Web/Css/Main.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="Web/Css/Front.css" />
		<?php echo $this->headLink();?>
		<?php echo $this->headScript();?>
		
	</head>
	<body>
		<header>
			<ul>
				<li>test</li>
			</ul>
		</header>
		
		<section id="content" >
			<?php  echo $content; ?>
		</section>
		
		<footer>
		</footer>
	</body>
</html>