<?php echo $this->headDoctype(),PHP_EOL;?>
<html lang="fr">
	<head>
		<?php echo $this->headTitle(),PHP_EOL;?>
		<?php echo $this->headMeta(),PHP_EOL;?>

		<link rel="stylesheet" type="text/css" media="screen" href="Css/Front.css" />
		<?php echo $this->headLink(),PHP_EOL;?>
		<?php echo $this->headScript(),PHP_EOL;?>
		
	</head>
	<body>
		<header>
			<ul>
				<li>test</li>
			</ul>
		</header>
		
		<section id="content" >
			<?php  echo $content; ?>
		</section>
		
		<footer>
		</footer>
	</body>
</html>