<?php echo $this->headDoctype(),PHP_EOL;?>
<html lang="fr">
	<head>
		<?php echo $this->headTitle(),PHP_EOL;?>
		<?php echo $this->headMeta(),PHP_EOL;?>
		<?php echo $this->headLink(),PHP_EOL;?>
		<?php echo $this->headScript(),PHP_EOL;?>
	</head>
	<body>
		
		<header id="Header"><?php echo $this->partial('Menu');?></header>
		
		<section id="Body">
			<section id="Explorer">
				<div id="SsExplorer"><?php echo $this->action('menu', 'Index')?></div>
			</section>
			
			<section id="Content">
				<div id="SsContent"><?php  echo $content; ?></div>
			</section>
		</section>
		
		<footer id="Footer"></footer>
		
	</body>
</html>