<?php echo $this->headDoctype();?>
<html lang="fr">
	<head>
		<?php echo $this->headTitle();?>
		<?php echo $this->headMeta();?>
		<link rel="stylesheet" type="text/css" media="screen" href="Css/ResetCSS.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="Css/Login.css" />
		<?php echo $this->headLink();?>
		<?php echo $this->headScript();?>
	</head>
	<body>

		
		<section id="content" >
			<?php echo $content; ?>
		</section>
		
		<footer>
		</footer>
	</body>
</html>