<div id="modalFormFTP" class="modal" data-title="Connexion FTP" data-origin="connexionftp.html" data-submit="ajaxconnexionftp.html">
	<div class="modal-content">
		Veuillez renseigner les champs suivants:<br /><br />
		<?php echo $formFTP;?>
	</div>
	<div class="modal-footer">
		<button class="btn btn-success" data-action="valid" data-reload="true">Valider</button>
		<button class="btn btn-danger" data-action="close">Fermer</button>
	</div>	
</div>
